name = "queensuperawesome"
author = "queen"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cf806eade92733630d7dbcab11715f924f885209ad6bad546f0c58114014b67"

[versions]
fabric = "0.11.2"
minecraft = "1.19.4"
