name = "queensuperawesome"
author = "queen"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7036115a43ca229fc3022bdbb4570d318c3cce021e4d0f10af0c16a08c6a0f8"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
