name = "queensuperawesome"
author = "queen"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "882c3014a9d7e24f934033e3326152df5fecd31adb5aa799e2d4da729bae1124"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
