name = "queensuperawesome"
author = "queen"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa6501de53a23bb87361b46a91876fef95faf3e417f736bbe089633a0fb26e59"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
